---
project_name: azenv
release:
  extra_files:
  - glob: ./bom.json
  github:
    owner: ericogr
    name: azenv
builds:
- main: ./
  binary: azenv
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  ldflags: -X github.com/ericogr/azenv/cmd.Version={{.Version}} -X github.com/ericogr/azenv/cmd.GitTag={{.Tag}} -X github.com/ericogr/azenv/cmd.BuildDate={{.Date}}
  env:
  - CGO_ENABLED=0